{% set name = "coin-or-utils" %}
{% set version = "2.11.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/coin-or/CoinUtils/archive/releases/{{ version }}.tar.gz
  sha256: 27da344479f38c82112d738501643dcb229e4ee96a5f87d4f406456bdc1b2cb4
  patches:
    - 0001-Patch-for-downstream.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, min_pin='x.x', max_pin='x.x') }}

requirements:
  build:
    - gnuconfig
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}  # [unix]
    - pkg-config  # [unix]
    - make  # [unix]
    - m2-make  # [win]
    - m2-pkg-config  # [win]
    - m2-grep  # [win]
    - m2-sed  # [win]
    - m2-bash  # [win]
    - m2-base  # [win]
    
  host:
    - blas-devel
    - libblas  # [unix]
    - libcblas
    - liblapack
    - liblapacke  # [unix]
    - zlib
    - bzip2
  
  run_constrained:
    - coincbc * *_metapackage

test:
  commands:
    - test -f $PREFIX/lib/libCoinUtils${SHLIB_EXT}         # [unix]
    - test -f $PREFIX/include/coin/CoinSort.hpp            # [unix]
    - if not exist %LIBRARY_LIB%/libCoinUtils.lib exit 1   # [win]
    - if not exist %LIBRARY_INC%/coin/CoinSort.hpp exit 1  # [win]
about:
  home: https://github.com/coin-or/CoinUtils
  dev_url: https://github.com/coin-or/CoinUtils
  license: EPL-2.0
  license_family: OTHER
  license_file: LICENSE
  summary: COIN-OR Utilities (CoinUtils)
  description: |
    CoinUtils (Coin-OR Utilities) is an open-source collection of classes and
    functions that are generally useful to more than one COIN-OR project. These
    utilities include:

      - classes for storing and manipulating sparse matrices and vectors,
      - performing matrix factorization,
      - parsing input files in standard formats, e.g. MPS,
      - building representations of mathematical programs,
      - performing simple presolve operations,
      - warm starting algorithms for mathematical programs, and
      - comparing floating point numbers with a tolerance, among others.

extra:
  recipe-maintainers:
    - wolfv
    - tkralphs
    - jschueller
    - jpfeuffer
